repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run task black
        pass_filenames: false
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run task isort
        pass_filenames: false
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run task mypy
        pass_filenames: false
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: debug-statements
